### ISSUE TITLE
Is there an easy way to disable switching theme AND also choosing the default theme?

### ISSUE THREAD

**Issue by eleijonmarck** [treefarmstudio/odyssey-theme#27]

**Comment by jaydanurwin** [comment]
Since this theme doesn't use something like Tailwind or a similar UI library you'll need to set the theme yourself in the CSS. However you can do this easily by going to `src/styles/theme.css`, remove all of the themes you don't want and set the one you'd like to the `:root` variables. 

If you're going to do that I'd also think about removing the themeswitcher and adding a simple script to remove the `theme` value from local storage if you'd already deployed the site live with the theme switcher enabled. If you haven't deployed it yet then just remove the theme switcher code. 

I hope that helps!
